/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sensedia.api.v3.model.APISimpleBean;
import com.sensedia.api.v3.model.AuthTokenSimpleBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * APP model
 */
@ApiModel(description = "APP model")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class APP {
  @JsonProperty("accessTokens")
  private List<AuthTokenSimpleBean> accessTokens = null;

  @JsonProperty("apis")
  private List<APISimpleBean> apis = null;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("creationDate")
  private DateTime creationDate = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("developer")
  private String developer = null;

  @JsonProperty("extraInfo")
  private Object extraInfo = null;

  @JsonProperty("icon")
  private String icon = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("link")
  private String link = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("secret")
  private String secret = null;

  @JsonProperty("showAppGallery")
  private Boolean showAppGallery = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    APPROVED("APPROVED"),
    
    PENDING("PENDING"),
    
    REJECTED("REJECTED"),
    
    CANCELLED("CANCELLED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  public APP accessTokens(List<AuthTokenSimpleBean> accessTokens) {
    this.accessTokens = accessTokens;
    return this;
  }

  public APP addAccessTokensItem(AuthTokenSimpleBean accessTokensItem) {
    if (this.accessTokens == null) {
      this.accessTokens = new ArrayList<AuthTokenSimpleBean>();
    }
    this.accessTokens.add(accessTokensItem);
    return this;
  }

   /**
   * Get accessTokens
   * @return accessTokens
  **/
  @ApiModelProperty(value = "")
  public List<AuthTokenSimpleBean> getAccessTokens() {
    return accessTokens;
  }

  public void setAccessTokens(List<AuthTokenSimpleBean> accessTokens) {
    this.accessTokens = accessTokens;
  }

  public APP apis(List<APISimpleBean> apis) {
    this.apis = apis;
    return this;
  }

  public APP addApisItem(APISimpleBean apisItem) {
    if (this.apis == null) {
      this.apis = new ArrayList<APISimpleBean>();
    }
    this.apis.add(apisItem);
    return this;
  }

   /**
   * Get apis
   * @return apis
  **/
  @ApiModelProperty(value = "")
  public List<APISimpleBean> getApis() {
    return apis;
  }

  public void setApis(List<APISimpleBean> apis) {
    this.apis = apis;
  }

  public APP clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public APP creationDate(DateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(DateTime creationDate) {
    this.creationDate = creationDate;
  }

  public APP description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public APP developer(String developer) {
    this.developer = developer;
    return this;
  }

   /**
   * Get developer
   * @return developer
  **/
  @ApiModelProperty(value = "")
  public String getDeveloper() {
    return developer;
  }

  public void setDeveloper(String developer) {
    this.developer = developer;
  }

  public APP extraInfo(Object extraInfo) {
    this.extraInfo = extraInfo;
    return this;
  }

   /**
   * Get extraInfo
   * @return extraInfo
  **/
  @ApiModelProperty(value = "")
  public Object getExtraInfo() {
    return extraInfo;
  }

  public void setExtraInfo(Object extraInfo) {
    this.extraInfo = extraInfo;
  }

  public APP icon(String icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon
  **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }

  public APP id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public APP link(String link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @ApiModelProperty(value = "")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }

  public APP name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public APP secret(String secret) {
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @ApiModelProperty(value = "")
  public String getSecret() {
    return secret;
  }

  public void setSecret(String secret) {
    this.secret = secret;
  }

  public APP showAppGallery(Boolean showAppGallery) {
    this.showAppGallery = showAppGallery;
    return this;
  }

   /**
   * Get showAppGallery
   * @return showAppGallery
  **/
  @ApiModelProperty(value = "")
  public Boolean getShowAppGallery() {
    return showAppGallery;
  }

  public void setShowAppGallery(Boolean showAppGallery) {
    this.showAppGallery = showAppGallery;
  }

  public APP status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APP APP = (APP) o;
    return Objects.equals(this.accessTokens, APP.accessTokens) &&
        Objects.equals(this.apis, APP.apis) &&
        Objects.equals(this.clientId, APP.clientId) &&
        Objects.equals(this.creationDate, APP.creationDate) &&
        Objects.equals(this.description, APP.description) &&
        Objects.equals(this.developer, APP.developer) &&
        Objects.equals(this.extraInfo, APP.extraInfo) &&
        Objects.equals(this.icon, APP.icon) &&
        Objects.equals(this.id, APP.id) &&
        Objects.equals(this.link, APP.link) &&
        Objects.equals(this.name, APP.name) &&
        Objects.equals(this.secret, APP.secret) &&
        Objects.equals(this.showAppGallery, APP.showAppGallery) &&
        Objects.equals(this.status, APP.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessTokens, apis, clientId, creationDate, description, developer, extraInfo, icon, id, link, name, secret, showAppGallery, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APP {\n");
    
    sb.append("    accessTokens: ").append(toIndentedString(accessTokens)).append("\n");
    sb.append("    apis: ").append(toIndentedString(apis)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    developer: ").append(toIndentedString(developer)).append("\n");
    sb.append("    extraInfo: ").append(toIndentedString(extraInfo)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    showAppGallery: ").append(toIndentedString(showAppGallery)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

