/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * Call
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-25T23:40:42.718-03:00")
public class Call {
  @JsonProperty("accessToken")
  private String accessToken = null;

  @JsonProperty("accessTokenOwner")
  private String accessTokenOwner = null;

  @JsonProperty("additionalData")
  private String additionalData = null;

  @JsonProperty("apiComponentType")
  private String apiComponentType = null;

  @JsonProperty("apiId")
  private Long apiId = null;

  @JsonProperty("apiName")
  private String apiName = null;

  @JsonProperty("appDeveloper")
  private String appDeveloper = null;

  @JsonProperty("appName")
  private String appName = null;

  @JsonProperty("appToken")
  private String appToken = null;

  @JsonProperty("authOwner")
  private String authOwner = null;

  @JsonProperty("baseUrl")
  private String baseUrl = null;

  @JsonProperty("billing")
  private Boolean billing = null;

  @JsonProperty("cache")
  private Boolean cache = null;

  @JsonProperty("callDate")
  private DateTime callDate = null;

  @JsonProperty("callerAddress")
  private String callerAddress = null;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("completeUrl")
  private String completeUrl = null;

  @JsonProperty("duration")
  private Integer duration = null;

  @JsonProperty("durationMillis")
  private Long durationMillis = null;

  @JsonProperty("environmentId")
  private Long environmentId = null;

  @JsonProperty("environmentName")
  private String environmentName = null;

  @JsonProperty("gatewayDurationMillis")
  private Long gatewayDurationMillis = null;

  @JsonProperty("httpStatus")
  private String httpStatus = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("insertedOnDate")
  private String insertedOnDate = null;

  @JsonProperty("method")
  private String method = null;

  @JsonProperty("operationId")
  private Long operationId = null;

  @JsonProperty("operationName")
  private String operationName = null;

  @JsonProperty("receivedFromAddress")
  private String receivedFromAddress = null;

  @JsonProperty("receivedOn")
  private Long receivedOn = null;

  @JsonProperty("receivedOnDate")
  private String receivedOnDate = null;

  @JsonProperty("redis")
  private Boolean redis = null;

  @JsonProperty("requestHeaders")
  private String requestHeaders = null;

  @JsonProperty("requestID")
  private String requestID = null;

  @JsonProperty("requestPayload")
  private Long requestPayload = null;

  @JsonProperty("resourceId")
  private Long resourceId = null;

  @JsonProperty("resourceName")
  private String resourceName = null;

  @JsonProperty("responseHeaders")
  private String responseHeaders = null;

  @JsonProperty("responsePayload")
  private Long responsePayload = null;

  @JsonProperty("resultStatus")
  private Integer resultStatus = null;

  @JsonProperty("revisionId")
  private Long revisionId = null;

  @JsonProperty("trace")
  private String trace = null;

  @JsonProperty("transactionID")
  private String transactionID = null;

  /**
   * Gets or Sets typeError
   */
  public enum TypeErrorEnum {
    CLIENT("client"),
    
    SERVER("server"),
    
    BLOCKED("blocked");

    private String value;

    TypeErrorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeErrorEnum fromValue(String text) {
      for (TypeErrorEnum b : TypeErrorEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("typeError")
  private TypeErrorEnum typeError = null;

  /**
   * Gets or Sets typeStatus
   */
  public enum TypeStatusEnum {
    SUCCESS("success"),
    
    ERROR("error");

    private String value;

    TypeStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeStatusEnum fromValue(String text) {
      for (TypeStatusEnum b : TypeStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("typeStatus")
  private TypeStatusEnum typeStatus = null;

  @JsonProperty("uri")
  private String uri = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("yearMonth")
  private String yearMonth = null;

  public Call accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * Get accessToken
   * @return accessToken
  **/
  @ApiModelProperty(value = "")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public Call accessTokenOwner(String accessTokenOwner) {
    this.accessTokenOwner = accessTokenOwner;
    return this;
  }

   /**
   * Get accessTokenOwner
   * @return accessTokenOwner
  **/
  @ApiModelProperty(value = "")
  public String getAccessTokenOwner() {
    return accessTokenOwner;
  }

  public void setAccessTokenOwner(String accessTokenOwner) {
    this.accessTokenOwner = accessTokenOwner;
  }

  public Call additionalData(String additionalData) {
    this.additionalData = additionalData;
    return this;
  }

   /**
   * Get additionalData
   * @return additionalData
  **/
  @ApiModelProperty(value = "")
  public String getAdditionalData() {
    return additionalData;
  }

  public void setAdditionalData(String additionalData) {
    this.additionalData = additionalData;
  }

  public Call apiComponentType(String apiComponentType) {
    this.apiComponentType = apiComponentType;
    return this;
  }

   /**
   * Get apiComponentType
   * @return apiComponentType
  **/
  @ApiModelProperty(value = "")
  public String getApiComponentType() {
    return apiComponentType;
  }

  public void setApiComponentType(String apiComponentType) {
    this.apiComponentType = apiComponentType;
  }

  public Call apiId(Long apiId) {
    this.apiId = apiId;
    return this;
  }

   /**
   * Get apiId
   * @return apiId
  **/
  @ApiModelProperty(value = "")
  public Long getApiId() {
    return apiId;
  }

  public void setApiId(Long apiId) {
    this.apiId = apiId;
  }

  public Call apiName(String apiName) {
    this.apiName = apiName;
    return this;
  }

   /**
   * Get apiName
   * @return apiName
  **/
  @ApiModelProperty(value = "")
  public String getApiName() {
    return apiName;
  }

  public void setApiName(String apiName) {
    this.apiName = apiName;
  }

  public Call appDeveloper(String appDeveloper) {
    this.appDeveloper = appDeveloper;
    return this;
  }

   /**
   * Get appDeveloper
   * @return appDeveloper
  **/
  @ApiModelProperty(value = "")
  public String getAppDeveloper() {
    return appDeveloper;
  }

  public void setAppDeveloper(String appDeveloper) {
    this.appDeveloper = appDeveloper;
  }

  public Call appName(String appName) {
    this.appName = appName;
    return this;
  }

   /**
   * Get appName
   * @return appName
  **/
  @ApiModelProperty(value = "")
  public String getAppName() {
    return appName;
  }

  public void setAppName(String appName) {
    this.appName = appName;
  }

  public Call appToken(String appToken) {
    this.appToken = appToken;
    return this;
  }

   /**
   * Get appToken
   * @return appToken
  **/
  @ApiModelProperty(value = "")
  public String getAppToken() {
    return appToken;
  }

  public void setAppToken(String appToken) {
    this.appToken = appToken;
  }

  public Call authOwner(String authOwner) {
    this.authOwner = authOwner;
    return this;
  }

   /**
   * Get authOwner
   * @return authOwner
  **/
  @ApiModelProperty(value = "")
  public String getAuthOwner() {
    return authOwner;
  }

  public void setAuthOwner(String authOwner) {
    this.authOwner = authOwner;
  }

  public Call baseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

   /**
   * Get baseUrl
   * @return baseUrl
  **/
  @ApiModelProperty(value = "")
  public String getBaseUrl() {
    return baseUrl;
  }

  public void setBaseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
  }

  public Call billing(Boolean billing) {
    this.billing = billing;
    return this;
  }

   /**
   * Get billing
   * @return billing
  **/
  @ApiModelProperty(value = "")
  public Boolean getBilling() {
    return billing;
  }

  public void setBilling(Boolean billing) {
    this.billing = billing;
  }

  public Call cache(Boolean cache) {
    this.cache = cache;
    return this;
  }

   /**
   * Get cache
   * @return cache
  **/
  @ApiModelProperty(value = "")
  public Boolean getCache() {
    return cache;
  }

  public void setCache(Boolean cache) {
    this.cache = cache;
  }

  public Call callDate(DateTime callDate) {
    this.callDate = callDate;
    return this;
  }

   /**
   * Get callDate
   * @return callDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getCallDate() {
    return callDate;
  }

  public void setCallDate(DateTime callDate) {
    this.callDate = callDate;
  }

  public Call callerAddress(String callerAddress) {
    this.callerAddress = callerAddress;
    return this;
  }

   /**
   * Get callerAddress
   * @return callerAddress
  **/
  @ApiModelProperty(value = "")
  public String getCallerAddress() {
    return callerAddress;
  }

  public void setCallerAddress(String callerAddress) {
    this.callerAddress = callerAddress;
  }

  public Call clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public Call completeUrl(String completeUrl) {
    this.completeUrl = completeUrl;
    return this;
  }

   /**
   * Get completeUrl
   * @return completeUrl
  **/
  @ApiModelProperty(value = "")
  public String getCompleteUrl() {
    return completeUrl;
  }

  public void setCompleteUrl(String completeUrl) {
    this.completeUrl = completeUrl;
  }

  public Call duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(value = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public Call durationMillis(Long durationMillis) {
    this.durationMillis = durationMillis;
    return this;
  }

   /**
   * Get durationMillis
   * @return durationMillis
  **/
  @ApiModelProperty(value = "")
  public Long getDurationMillis() {
    return durationMillis;
  }

  public void setDurationMillis(Long durationMillis) {
    this.durationMillis = durationMillis;
  }

  public Call environmentId(Long environmentId) {
    this.environmentId = environmentId;
    return this;
  }

   /**
   * Get environmentId
   * @return environmentId
  **/
  @ApiModelProperty(value = "")
  public Long getEnvironmentId() {
    return environmentId;
  }

  public void setEnvironmentId(Long environmentId) {
    this.environmentId = environmentId;
  }

  public Call environmentName(String environmentName) {
    this.environmentName = environmentName;
    return this;
  }

   /**
   * Get environmentName
   * @return environmentName
  **/
  @ApiModelProperty(value = "")
  public String getEnvironmentName() {
    return environmentName;
  }

  public void setEnvironmentName(String environmentName) {
    this.environmentName = environmentName;
  }

  public Call gatewayDurationMillis(Long gatewayDurationMillis) {
    this.gatewayDurationMillis = gatewayDurationMillis;
    return this;
  }

   /**
   * Get gatewayDurationMillis
   * @return gatewayDurationMillis
  **/
  @ApiModelProperty(value = "")
  public Long getGatewayDurationMillis() {
    return gatewayDurationMillis;
  }

  public void setGatewayDurationMillis(Long gatewayDurationMillis) {
    this.gatewayDurationMillis = gatewayDurationMillis;
  }

  public Call httpStatus(String httpStatus) {
    this.httpStatus = httpStatus;
    return this;
  }

   /**
   * Get httpStatus
   * @return httpStatus
  **/
  @ApiModelProperty(value = "")
  public String getHttpStatus() {
    return httpStatus;
  }

  public void setHttpStatus(String httpStatus) {
    this.httpStatus = httpStatus;
  }

  public Call id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Call insertedOnDate(String insertedOnDate) {
    this.insertedOnDate = insertedOnDate;
    return this;
  }

   /**
   * Get insertedOnDate
   * @return insertedOnDate
  **/
  @ApiModelProperty(value = "")
  public String getInsertedOnDate() {
    return insertedOnDate;
  }

  public void setInsertedOnDate(String insertedOnDate) {
    this.insertedOnDate = insertedOnDate;
  }

  public Call method(String method) {
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @ApiModelProperty(value = "")
  public String getMethod() {
    return method;
  }

  public void setMethod(String method) {
    this.method = method;
  }

  public Call operationId(Long operationId) {
    this.operationId = operationId;
    return this;
  }

   /**
   * Get operationId
   * @return operationId
  **/
  @ApiModelProperty(value = "")
  public Long getOperationId() {
    return operationId;
  }

  public void setOperationId(Long operationId) {
    this.operationId = operationId;
  }

  public Call operationName(String operationName) {
    this.operationName = operationName;
    return this;
  }

   /**
   * Get operationName
   * @return operationName
  **/
  @ApiModelProperty(value = "")
  public String getOperationName() {
    return operationName;
  }

  public void setOperationName(String operationName) {
    this.operationName = operationName;
  }

  public Call receivedFromAddress(String receivedFromAddress) {
    this.receivedFromAddress = receivedFromAddress;
    return this;
  }

   /**
   * Get receivedFromAddress
   * @return receivedFromAddress
  **/
  @ApiModelProperty(value = "")
  public String getReceivedFromAddress() {
    return receivedFromAddress;
  }

  public void setReceivedFromAddress(String receivedFromAddress) {
    this.receivedFromAddress = receivedFromAddress;
  }

  public Call receivedOn(Long receivedOn) {
    this.receivedOn = receivedOn;
    return this;
  }

   /**
   * Get receivedOn
   * @return receivedOn
  **/
  @ApiModelProperty(value = "")
  public Long getReceivedOn() {
    return receivedOn;
  }

  public void setReceivedOn(Long receivedOn) {
    this.receivedOn = receivedOn;
  }

  public Call receivedOnDate(String receivedOnDate) {
    this.receivedOnDate = receivedOnDate;
    return this;
  }

   /**
   * Get receivedOnDate
   * @return receivedOnDate
  **/
  @ApiModelProperty(value = "")
  public String getReceivedOnDate() {
    return receivedOnDate;
  }

  public void setReceivedOnDate(String receivedOnDate) {
    this.receivedOnDate = receivedOnDate;
  }

  public Call redis(Boolean redis) {
    this.redis = redis;
    return this;
  }

   /**
   * Get redis
   * @return redis
  **/
  @ApiModelProperty(value = "")
  public Boolean getRedis() {
    return redis;
  }

  public void setRedis(Boolean redis) {
    this.redis = redis;
  }

  public Call requestHeaders(String requestHeaders) {
    this.requestHeaders = requestHeaders;
    return this;
  }

   /**
   * Get requestHeaders
   * @return requestHeaders
  **/
  @ApiModelProperty(value = "")
  public String getRequestHeaders() {
    return requestHeaders;
  }

  public void setRequestHeaders(String requestHeaders) {
    this.requestHeaders = requestHeaders;
  }

  public Call requestID(String requestID) {
    this.requestID = requestID;
    return this;
  }

   /**
   * Get requestID
   * @return requestID
  **/
  @ApiModelProperty(value = "")
  public String getRequestID() {
    return requestID;
  }

  public void setRequestID(String requestID) {
    this.requestID = requestID;
  }

  public Call requestPayload(Long requestPayload) {
    this.requestPayload = requestPayload;
    return this;
  }

   /**
   * Get requestPayload
   * @return requestPayload
  **/
  @ApiModelProperty(value = "")
  public Long getRequestPayload() {
    return requestPayload;
  }

  public void setRequestPayload(Long requestPayload) {
    this.requestPayload = requestPayload;
  }

  public Call resourceId(Long resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @ApiModelProperty(value = "")
  public Long getResourceId() {
    return resourceId;
  }

  public void setResourceId(Long resourceId) {
    this.resourceId = resourceId;
  }

  public Call resourceName(String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

   /**
   * Get resourceName
   * @return resourceName
  **/
  @ApiModelProperty(value = "")
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(String resourceName) {
    this.resourceName = resourceName;
  }

  public Call responseHeaders(String responseHeaders) {
    this.responseHeaders = responseHeaders;
    return this;
  }

   /**
   * Get responseHeaders
   * @return responseHeaders
  **/
  @ApiModelProperty(value = "")
  public String getResponseHeaders() {
    return responseHeaders;
  }

  public void setResponseHeaders(String responseHeaders) {
    this.responseHeaders = responseHeaders;
  }

  public Call responsePayload(Long responsePayload) {
    this.responsePayload = responsePayload;
    return this;
  }

   /**
   * Get responsePayload
   * @return responsePayload
  **/
  @ApiModelProperty(value = "")
  public Long getResponsePayload() {
    return responsePayload;
  }

  public void setResponsePayload(Long responsePayload) {
    this.responsePayload = responsePayload;
  }

  public Call resultStatus(Integer resultStatus) {
    this.resultStatus = resultStatus;
    return this;
  }

   /**
   * Get resultStatus
   * @return resultStatus
  **/
  @ApiModelProperty(value = "")
  public Integer getResultStatus() {
    return resultStatus;
  }

  public void setResultStatus(Integer resultStatus) {
    this.resultStatus = resultStatus;
  }

  public Call revisionId(Long revisionId) {
    this.revisionId = revisionId;
    return this;
  }

   /**
   * Get revisionId
   * @return revisionId
  **/
  @ApiModelProperty(value = "")
  public Long getRevisionId() {
    return revisionId;
  }

  public void setRevisionId(Long revisionId) {
    this.revisionId = revisionId;
  }

  public Call trace(String trace) {
    this.trace = trace;
    return this;
  }

   /**
   * Get trace
   * @return trace
  **/
  @ApiModelProperty(value = "")
  public String getTrace() {
    return trace;
  }

  public void setTrace(String trace) {
    this.trace = trace;
  }

  public Call transactionID(String transactionID) {
    this.transactionID = transactionID;
    return this;
  }

   /**
   * Get transactionID
   * @return transactionID
  **/
  @ApiModelProperty(value = "")
  public String getTransactionID() {
    return transactionID;
  }

  public void setTransactionID(String transactionID) {
    this.transactionID = transactionID;
  }

  public Call typeError(TypeErrorEnum typeError) {
    this.typeError = typeError;
    return this;
  }

   /**
   * Get typeError
   * @return typeError
  **/
  @ApiModelProperty(value = "")
  public TypeErrorEnum getTypeError() {
    return typeError;
  }

  public void setTypeError(TypeErrorEnum typeError) {
    this.typeError = typeError;
  }

  public Call typeStatus(TypeStatusEnum typeStatus) {
    this.typeStatus = typeStatus;
    return this;
  }

   /**
   * Get typeStatus
   * @return typeStatus
  **/
  @ApiModelProperty(value = "")
  public TypeStatusEnum getTypeStatus() {
    return typeStatus;
  }

  public void setTypeStatus(TypeStatusEnum typeStatus) {
    this.typeStatus = typeStatus;
  }

  public Call uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public Call url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Call yearMonth(String yearMonth) {
    this.yearMonth = yearMonth;
    return this;
  }

   /**
   * Get yearMonth
   * @return yearMonth
  **/
  @ApiModelProperty(value = "")
  public String getYearMonth() {
    return yearMonth;
  }

  public void setYearMonth(String yearMonth) {
    this.yearMonth = yearMonth;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Call call = (Call) o;
    return Objects.equals(this.accessToken, call.accessToken) &&
        Objects.equals(this.accessTokenOwner, call.accessTokenOwner) &&
        Objects.equals(this.additionalData, call.additionalData) &&
        Objects.equals(this.apiComponentType, call.apiComponentType) &&
        Objects.equals(this.apiId, call.apiId) &&
        Objects.equals(this.apiName, call.apiName) &&
        Objects.equals(this.appDeveloper, call.appDeveloper) &&
        Objects.equals(this.appName, call.appName) &&
        Objects.equals(this.appToken, call.appToken) &&
        Objects.equals(this.authOwner, call.authOwner) &&
        Objects.equals(this.baseUrl, call.baseUrl) &&
        Objects.equals(this.billing, call.billing) &&
        Objects.equals(this.cache, call.cache) &&
        Objects.equals(this.callDate, call.callDate) &&
        Objects.equals(this.callerAddress, call.callerAddress) &&
        Objects.equals(this.clientId, call.clientId) &&
        Objects.equals(this.completeUrl, call.completeUrl) &&
        Objects.equals(this.duration, call.duration) &&
        Objects.equals(this.durationMillis, call.durationMillis) &&
        Objects.equals(this.environmentId, call.environmentId) &&
        Objects.equals(this.environmentName, call.environmentName) &&
        Objects.equals(this.gatewayDurationMillis, call.gatewayDurationMillis) &&
        Objects.equals(this.httpStatus, call.httpStatus) &&
        Objects.equals(this.id, call.id) &&
        Objects.equals(this.insertedOnDate, call.insertedOnDate) &&
        Objects.equals(this.method, call.method) &&
        Objects.equals(this.operationId, call.operationId) &&
        Objects.equals(this.operationName, call.operationName) &&
        Objects.equals(this.receivedFromAddress, call.receivedFromAddress) &&
        Objects.equals(this.receivedOn, call.receivedOn) &&
        Objects.equals(this.receivedOnDate, call.receivedOnDate) &&
        Objects.equals(this.redis, call.redis) &&
        Objects.equals(this.requestHeaders, call.requestHeaders) &&
        Objects.equals(this.requestID, call.requestID) &&
        Objects.equals(this.requestPayload, call.requestPayload) &&
        Objects.equals(this.resourceId, call.resourceId) &&
        Objects.equals(this.resourceName, call.resourceName) &&
        Objects.equals(this.responseHeaders, call.responseHeaders) &&
        Objects.equals(this.responsePayload, call.responsePayload) &&
        Objects.equals(this.resultStatus, call.resultStatus) &&
        Objects.equals(this.revisionId, call.revisionId) &&
        Objects.equals(this.trace, call.trace) &&
        Objects.equals(this.transactionID, call.transactionID) &&
        Objects.equals(this.typeError, call.typeError) &&
        Objects.equals(this.typeStatus, call.typeStatus) &&
        Objects.equals(this.uri, call.uri) &&
        Objects.equals(this.url, call.url) &&
        Objects.equals(this.yearMonth, call.yearMonth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, accessTokenOwner, additionalData, apiComponentType, apiId, apiName, appDeveloper, appName, appToken, authOwner, baseUrl, billing, cache, callDate, callerAddress, clientId, completeUrl, duration, durationMillis, environmentId, environmentName, gatewayDurationMillis, httpStatus, id, insertedOnDate, method, operationId, operationName, receivedFromAddress, receivedOn, receivedOnDate, redis, requestHeaders, requestID, requestPayload, resourceId, resourceName, responseHeaders, responsePayload, resultStatus, revisionId, trace, transactionID, typeError, typeStatus, uri, url, yearMonth);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Call {\n");
    
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    accessTokenOwner: ").append(toIndentedString(accessTokenOwner)).append("\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    apiComponentType: ").append(toIndentedString(apiComponentType)).append("\n");
    sb.append("    apiId: ").append(toIndentedString(apiId)).append("\n");
    sb.append("    apiName: ").append(toIndentedString(apiName)).append("\n");
    sb.append("    appDeveloper: ").append(toIndentedString(appDeveloper)).append("\n");
    sb.append("    appName: ").append(toIndentedString(appName)).append("\n");
    sb.append("    appToken: ").append(toIndentedString(appToken)).append("\n");
    sb.append("    authOwner: ").append(toIndentedString(authOwner)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    billing: ").append(toIndentedString(billing)).append("\n");
    sb.append("    cache: ").append(toIndentedString(cache)).append("\n");
    sb.append("    callDate: ").append(toIndentedString(callDate)).append("\n");
    sb.append("    callerAddress: ").append(toIndentedString(callerAddress)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    completeUrl: ").append(toIndentedString(completeUrl)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    durationMillis: ").append(toIndentedString(durationMillis)).append("\n");
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    environmentName: ").append(toIndentedString(environmentName)).append("\n");
    sb.append("    gatewayDurationMillis: ").append(toIndentedString(gatewayDurationMillis)).append("\n");
    sb.append("    httpStatus: ").append(toIndentedString(httpStatus)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    insertedOnDate: ").append(toIndentedString(insertedOnDate)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    operationName: ").append(toIndentedString(operationName)).append("\n");
    sb.append("    receivedFromAddress: ").append(toIndentedString(receivedFromAddress)).append("\n");
    sb.append("    receivedOn: ").append(toIndentedString(receivedOn)).append("\n");
    sb.append("    receivedOnDate: ").append(toIndentedString(receivedOnDate)).append("\n");
    sb.append("    redis: ").append(toIndentedString(redis)).append("\n");
    sb.append("    requestHeaders: ").append(toIndentedString(requestHeaders)).append("\n");
    sb.append("    requestID: ").append(toIndentedString(requestID)).append("\n");
    sb.append("    requestPayload: ").append(toIndentedString(requestPayload)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    responseHeaders: ").append(toIndentedString(responseHeaders)).append("\n");
    sb.append("    responsePayload: ").append(toIndentedString(responsePayload)).append("\n");
    sb.append("    resultStatus: ").append(toIndentedString(resultStatus)).append("\n");
    sb.append("    revisionId: ").append(toIndentedString(revisionId)).append("\n");
    sb.append("    trace: ").append(toIndentedString(trace)).append("\n");
    sb.append("    transactionID: ").append(toIndentedString(transactionID)).append("\n");
    sb.append("    typeError: ").append(toIndentedString(typeError)).append("\n");
    sb.append("    typeStatus: ").append(toIndentedString(typeStatus)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    yearMonth: ").append(toIndentedString(yearMonth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

