/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * CallsMetric
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class CallsMetric {
  @JsonProperty("blocked")
  private Long blocked = null;

  @JsonProperty("clientError")
  private Long clientError = null;

  @JsonProperty("count")
  private Long count = null;

  @JsonProperty("date")
  private DateTime date = null;

  @JsonProperty("error")
  private Long error = null;

  @JsonProperty("serverError")
  private Long serverError = null;

  @JsonProperty("success")
  private Long success = null;

  public CallsMetric blocked(Long blocked) {
    this.blocked = blocked;
    return this;
  }

   /**
   * Get blocked
   * @return blocked
  **/
  @ApiModelProperty(value = "")
  public Long getBlocked() {
    return blocked;
  }

  public void setBlocked(Long blocked) {
    this.blocked = blocked;
  }

  public CallsMetric clientError(Long clientError) {
    this.clientError = clientError;
    return this;
  }

   /**
   * Get clientError
   * @return clientError
  **/
  @ApiModelProperty(value = "")
  public Long getClientError() {
    return clientError;
  }

  public void setClientError(Long clientError) {
    this.clientError = clientError;
  }

  public CallsMetric count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public CallsMetric date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public CallsMetric error(Long error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Long getError() {
    return error;
  }

  public void setError(Long error) {
    this.error = error;
  }

  public CallsMetric serverError(Long serverError) {
    this.serverError = serverError;
    return this;
  }

   /**
   * Get serverError
   * @return serverError
  **/
  @ApiModelProperty(value = "")
  public Long getServerError() {
    return serverError;
  }

  public void setServerError(Long serverError) {
    this.serverError = serverError;
  }

  public CallsMetric success(Long success) {
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @ApiModelProperty(value = "")
  public Long getSuccess() {
    return success;
  }

  public void setSuccess(Long success) {
    this.success = success;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallsMetric callsMetric = (CallsMetric) o;
    return Objects.equals(this.blocked, callsMetric.blocked) &&
        Objects.equals(this.clientError, callsMetric.clientError) &&
        Objects.equals(this.count, callsMetric.count) &&
        Objects.equals(this.date, callsMetric.date) &&
        Objects.equals(this.error, callsMetric.error) &&
        Objects.equals(this.serverError, callsMetric.serverError) &&
        Objects.equals(this.success, callsMetric.success);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blocked, clientError, count, date, error, serverError, success);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallsMetric {\n");
    
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    clientError: ").append(toIndentedString(clientError)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    serverError: ").append(toIndentedString(serverError)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

