/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sensedia.api.v3.model.Call;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CallResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class CallResponse {
  @JsonProperty("calls")
  private List<Call> calls = null;

  @JsonProperty("callsSize")
  private Long callsSize = null;

  public CallResponse calls(List<Call> calls) {
    this.calls = calls;
    return this;
  }

  public CallResponse addCallsItem(Call callsItem) {
    if (this.calls == null) {
      this.calls = new ArrayList<Call>();
    }
    this.calls.add(callsItem);
    return this;
  }

   /**
   * Get calls
   * @return calls
  **/
  @ApiModelProperty(value = "")
  public List<Call> getCalls() {
    return calls;
  }

  public void setCalls(List<Call> calls) {
    this.calls = calls;
  }

  public CallResponse callsSize(Long callsSize) {
    this.callsSize = callsSize;
    return this;
  }

   /**
   * Get callsSize
   * @return callsSize
  **/
  @ApiModelProperty(value = "")
  public Long getCallsSize() {
    return callsSize;
  }

  public void setCallsSize(Long callsSize) {
    this.callsSize = callsSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallResponse callResponse = (CallResponse) o;
    return Objects.equals(this.calls, callResponse.calls) &&
        Objects.equals(this.callsSize, callResponse.callsSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calls, callsSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallResponse {\n");
    
    sb.append("    calls: ").append(toIndentedString(calls)).append("\n");
    sb.append("    callsSize: ").append(toIndentedString(callsSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

