/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sensedia.api.v3.model.DeploymentBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * DeploymentScheduleBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class DeploymentScheduleBean {
  @JsonProperty("creationDate")
  private DateTime creationDate = null;

  @JsonProperty("deployments")
  private List<DeploymentBean> deployments = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("scheduleDate")
  private DateTime scheduleDate = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    SCHEDULED("SCHEDULED"),
    
    SUCCESS("SUCCESS"),
    
    ERROR("ERROR");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  public DeploymentScheduleBean creationDate(DateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(DateTime creationDate) {
    this.creationDate = creationDate;
  }

  public DeploymentScheduleBean deployments(List<DeploymentBean> deployments) {
    this.deployments = deployments;
    return this;
  }

  public DeploymentScheduleBean addDeploymentsItem(DeploymentBean deploymentsItem) {
    if (this.deployments == null) {
      this.deployments = new ArrayList<DeploymentBean>();
    }
    this.deployments.add(deploymentsItem);
    return this;
  }

   /**
   * Get deployments
   * @return deployments
  **/
  @ApiModelProperty(value = "")
  public List<DeploymentBean> getDeployments() {
    return deployments;
  }

  public void setDeployments(List<DeploymentBean> deployments) {
    this.deployments = deployments;
  }

  public DeploymentScheduleBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DeploymentScheduleBean name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeploymentScheduleBean scheduleDate(DateTime scheduleDate) {
    this.scheduleDate = scheduleDate;
    return this;
  }

   /**
   * Get scheduleDate
   * @return scheduleDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getScheduleDate() {
    return scheduleDate;
  }

  public void setScheduleDate(DateTime scheduleDate) {
    this.scheduleDate = scheduleDate;
  }

  public DeploymentScheduleBean status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentScheduleBean deploymentScheduleBean = (DeploymentScheduleBean) o;
    return Objects.equals(this.creationDate, deploymentScheduleBean.creationDate) &&
        Objects.equals(this.deployments, deploymentScheduleBean.deployments) &&
        Objects.equals(this.id, deploymentScheduleBean.id) &&
        Objects.equals(this.name, deploymentScheduleBean.name) &&
        Objects.equals(this.scheduleDate, deploymentScheduleBean.scheduleDate) &&
        Objects.equals(this.status, deploymentScheduleBean.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, deployments, id, name, scheduleDate, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentScheduleBean {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    deployments: ").append(toIndentedString(deployments)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    scheduleDate: ").append(toIndentedString(scheduleDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

