/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * LatencyMetric
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class LatencyMetric {
  @JsonProperty("count")
  private Long count = null;

  @JsonProperty("date")
  private DateTime date = null;

  @JsonProperty("latencyMillis")
  private Long latencyMillis = null;

  @JsonProperty("totalLatency")
  private Long totalLatency = null;

  public LatencyMetric count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public LatencyMetric date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public LatencyMetric latencyMillis(Long latencyMillis) {
    this.latencyMillis = latencyMillis;
    return this;
  }

   /**
   * Get latencyMillis
   * @return latencyMillis
  **/
  @ApiModelProperty(value = "")
  public Long getLatencyMillis() {
    return latencyMillis;
  }

  public void setLatencyMillis(Long latencyMillis) {
    this.latencyMillis = latencyMillis;
  }

  public LatencyMetric totalLatency(Long totalLatency) {
    this.totalLatency = totalLatency;
    return this;
  }

   /**
   * Get totalLatency
   * @return totalLatency
  **/
  @ApiModelProperty(value = "")
  public Long getTotalLatency() {
    return totalLatency;
  }

  public void setTotalLatency(Long totalLatency) {
    this.totalLatency = totalLatency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LatencyMetric latencyMetric = (LatencyMetric) o;
    return Objects.equals(this.count, latencyMetric.count) &&
        Objects.equals(this.date, latencyMetric.date) &&
        Objects.equals(this.latencyMillis, latencyMetric.latencyMillis) &&
        Objects.equals(this.totalLatency, latencyMetric.totalLatency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, date, latencyMillis, totalLatency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LatencyMetric {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    latencyMillis: ").append(toIndentedString(latencyMillis)).append("\n");
    sb.append("    totalLatency: ").append(toIndentedString(totalLatency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

