/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * OperationHealth
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class OperationHealth {
  @JsonProperty("last24Hours")
  private Double last24Hours = null;

  @JsonProperty("lastHour")
  private Double lastHour = null;

  @JsonProperty("lastMonth")
  private Double lastMonth = null;

  @JsonProperty("lastWeek")
  private Double lastWeek = null;

  @JsonProperty("operation")
  private String operation = null;

  public OperationHealth last24Hours(Double last24Hours) {
    this.last24Hours = last24Hours;
    return this;
  }

   /**
   * Get last24Hours
   * @return last24Hours
  **/
  @ApiModelProperty(value = "")
  public Double getLast24Hours() {
    return last24Hours;
  }

  public void setLast24Hours(Double last24Hours) {
    this.last24Hours = last24Hours;
  }

  public OperationHealth lastHour(Double lastHour) {
    this.lastHour = lastHour;
    return this;
  }

   /**
   * Get lastHour
   * @return lastHour
  **/
  @ApiModelProperty(value = "")
  public Double getLastHour() {
    return lastHour;
  }

  public void setLastHour(Double lastHour) {
    this.lastHour = lastHour;
  }

  public OperationHealth lastMonth(Double lastMonth) {
    this.lastMonth = lastMonth;
    return this;
  }

   /**
   * Get lastMonth
   * @return lastMonth
  **/
  @ApiModelProperty(value = "")
  public Double getLastMonth() {
    return lastMonth;
  }

  public void setLastMonth(Double lastMonth) {
    this.lastMonth = lastMonth;
  }

  public OperationHealth lastWeek(Double lastWeek) {
    this.lastWeek = lastWeek;
    return this;
  }

   /**
   * Get lastWeek
   * @return lastWeek
  **/
  @ApiModelProperty(value = "")
  public Double getLastWeek() {
    return lastWeek;
  }

  public void setLastWeek(Double lastWeek) {
    this.lastWeek = lastWeek;
  }

  public OperationHealth operation(String operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @ApiModelProperty(value = "")
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationHealth operationHealth = (OperationHealth) o;
    return Objects.equals(this.last24Hours, operationHealth.last24Hours) &&
        Objects.equals(this.lastHour, operationHealth.lastHour) &&
        Objects.equals(this.lastMonth, operationHealth.lastMonth) &&
        Objects.equals(this.lastWeek, operationHealth.lastWeek) &&
        Objects.equals(this.operation, operationHealth.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(last24Hours, lastHour, lastMonth, lastWeek, operation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationHealth {\n");
    
    sb.append("    last24Hours: ").append(toIndentedString(last24Hours)).append("\n");
    sb.append("    lastHour: ").append(toIndentedString(lastHour)).append("\n");
    sb.append("    lastMonth: ").append(toIndentedString(lastMonth)).append("\n");
    sb.append("    lastWeek: ").append(toIndentedString(lastWeek)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

