/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sensedia.api.v3.model.APISimpleBean;
import com.sensedia.api.v3.model.InterceptorBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Response create or update plan
 */
@ApiModel(description = "Response create or update plan")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class PlanResponse {
  @JsonProperty("api")
  private APISimpleBean api = null;

  @JsonProperty("defaultPlan")
  private Boolean defaultPlan = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("interceptors")
  private List<InterceptorBean> interceptors = null;

  @JsonProperty("name")
  private String name = null;

  public PlanResponse api(APISimpleBean api) {
    this.api = api;
    return this;
  }

   /**
   * Get api
   * @return api
  **/
  @ApiModelProperty(value = "")
  public APISimpleBean getApi() {
    return api;
  }

  public void setApi(APISimpleBean api) {
    this.api = api;
  }

  public PlanResponse defaultPlan(Boolean defaultPlan) {
    this.defaultPlan = defaultPlan;
    return this;
  }

   /**
   * Get defaultPlan
   * @return defaultPlan
  **/
  @ApiModelProperty(value = "")
  public Boolean getDefaultPlan() {
    return defaultPlan;
  }

  public void setDefaultPlan(Boolean defaultPlan) {
    this.defaultPlan = defaultPlan;
  }

  public PlanResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PlanResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PlanResponse interceptors(List<InterceptorBean> interceptors) {
    this.interceptors = interceptors;
    return this;
  }

  public PlanResponse addInterceptorsItem(InterceptorBean interceptorsItem) {
    if (this.interceptors == null) {
      this.interceptors = new ArrayList<InterceptorBean>();
    }
    this.interceptors.add(interceptorsItem);
    return this;
  }

   /**
   * Get interceptors
   * @return interceptors
  **/
  @ApiModelProperty(value = "")
  public List<InterceptorBean> getInterceptors() {
    return interceptors;
  }

  public void setInterceptors(List<InterceptorBean> interceptors) {
    this.interceptors = interceptors;
  }

  public PlanResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanResponse planResponse = (PlanResponse) o;
    return Objects.equals(this.api, planResponse.api) &&
        Objects.equals(this.defaultPlan, planResponse.defaultPlan) &&
        Objects.equals(this.description, planResponse.description) &&
        Objects.equals(this.id, planResponse.id) &&
        Objects.equals(this.interceptors, planResponse.interceptors) &&
        Objects.equals(this.name, planResponse.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(api, defaultPlan, description, id, interceptors, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanResponse {\n");
    
    sb.append("    api: ").append(toIndentedString(api)).append("\n");
    sb.append("    defaultPlan: ").append(toIndentedString(defaultPlan)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    interceptors: ").append(toIndentedString(interceptors)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

