/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sensedia.api.v3.model.InterceptorBean;
import com.sensedia.api.v3.model.OperationBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ResourceBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-25T23:40:42.718-03:00")
public class ResourceBean {
  @JsonProperty("apiBroken")
  private Boolean apiBroken = null;

  @JsonProperty("config")
  private Object config = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("destination")
  private String destination = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("interceptors")
  private List<InterceptorBean> interceptors = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("operations")
  private List<OperationBean> operations = null;

  @JsonProperty("timeout")
  private String timeout = null;

  public ResourceBean apiBroken(Boolean apiBroken) {
    this.apiBroken = apiBroken;
    return this;
  }

   /**
   * Get apiBroken
   * @return apiBroken
  **/
  @ApiModelProperty(value = "")
  public Boolean getApiBroken() {
    return apiBroken;
  }

  public void setApiBroken(Boolean apiBroken) {
    this.apiBroken = apiBroken;
  }

  public ResourceBean config(Object config) {
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @ApiModelProperty(value = "")
  public Object getConfig() {
    return config;
  }

  public void setConfig(Object config) {
    this.config = config;
  }

  public ResourceBean description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ResourceBean destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  @ApiModelProperty(value = "")
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }

  public ResourceBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ResourceBean interceptors(List<InterceptorBean> interceptors) {
    this.interceptors = interceptors;
    return this;
  }

  public ResourceBean addInterceptorsItem(InterceptorBean interceptorsItem) {
    if (this.interceptors == null) {
      this.interceptors = new ArrayList<InterceptorBean>();
    }
    this.interceptors.add(interceptorsItem);
    return this;
  }

   /**
   * Get interceptors
   * @return interceptors
  **/
  @ApiModelProperty(value = "")
  public List<InterceptorBean> getInterceptors() {
    return interceptors;
  }

  public void setInterceptors(List<InterceptorBean> interceptors) {
    this.interceptors = interceptors;
  }

  public ResourceBean name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResourceBean operations(List<OperationBean> operations) {
    this.operations = operations;
    return this;
  }

  public ResourceBean addOperationsItem(OperationBean operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<OperationBean>();
    }
    this.operations.add(operationsItem);
    return this;
  }

   /**
   * Get operations
   * @return operations
  **/
  @ApiModelProperty(value = "")
  public List<OperationBean> getOperations() {
    return operations;
  }

  public void setOperations(List<OperationBean> operations) {
    this.operations = operations;
  }

  public ResourceBean timeout(String timeout) {
    this.timeout = timeout;
    return this;
  }

   /**
   * Get timeout
   * @return timeout
  **/
  @ApiModelProperty(value = "")
  public String getTimeout() {
    return timeout;
  }

  public void setTimeout(String timeout) {
    this.timeout = timeout;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceBean resourceBean = (ResourceBean) o;
    return Objects.equals(this.apiBroken, resourceBean.apiBroken) &&
        Objects.equals(this.config, resourceBean.config) &&
        Objects.equals(this.description, resourceBean.description) &&
        Objects.equals(this.destination, resourceBean.destination) &&
        Objects.equals(this.id, resourceBean.id) &&
        Objects.equals(this.interceptors, resourceBean.interceptors) &&
        Objects.equals(this.name, resourceBean.name) &&
        Objects.equals(this.operations, resourceBean.operations) &&
        Objects.equals(this.timeout, resourceBean.timeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiBroken, config, description, destination, id, interceptors, name, operations, timeout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceBean {\n");
    
    sb.append("    apiBroken: ").append(toIndentedString(apiBroken)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    interceptors: ").append(toIndentedString(interceptors)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

