/*
 * API Manager Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sensedia.api.v3.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RolePermissionBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-06T11:21:38.562-03:00")
public class RolePermissionBean {
  @JsonProperty("id")
  private Long id = null;

  /**
   * Gets or Sets permission
   */
  public enum PermissionEnum {
    DASHBOARD("DASHBOARD"),
    
    ANALYTICS("ANALYTICS"),
    
    APIS_HEALTH("APIS_HEALTH"),
    
    APIS("APIS"),
    
    BAAS("BAAS"),
    
    NOTIFICATIONS("NOTIFICATIONS"),
    
    PLANS("PLANS"),
    
    APPS("APPS"),
    
    ACCESS_TOKENS("ACCESS_TOKENS"),
    
    SECRETS("SECRETS"),
    
    DEVELOPERS("DEVELOPERS"),
    
    TRACE("TRACE"),
    
    ENVIRONMENTS("ENVIRONMENTS"),
    
    CALLBACKS("CALLBACKS"),
    
    HEALTH_CHECKS("HEALTH_CHECKS"),
    
    USERS("USERS"),
    
    ROLES("ROLES"),
    
    TEAMS("TEAMS"),
    
    AUDIT("AUDIT"),
    
    OAUTH("OAUTH"),
    
    LDAP("LDAP"),
    
    ROOT("ROOT"),
    
    NONE("NONE"),
    
    ALERT("ALERT"),
    
    MAIL_SETTINGS("MAIL_SETTINGS");

    private String value;

    PermissionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PermissionEnum fromValue(String text) {
      for (PermissionEnum b : PermissionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("permission")
  private PermissionEnum permission = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    VIEW("VIEW"),
    
    EDIT("EDIT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  public RolePermissionBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public RolePermissionBean permission(PermissionEnum permission) {
    this.permission = permission;
    return this;
  }

   /**
   * Get permission
   * @return permission
  **/
  @ApiModelProperty(value = "")
  public PermissionEnum getPermission() {
    return permission;
  }

  public void setPermission(PermissionEnum permission) {
    this.permission = permission;
  }

  public RolePermissionBean type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RolePermissionBean rolePermissionBean = (RolePermissionBean) o;
    return Objects.equals(this.id, rolePermissionBean.id) &&
        Objects.equals(this.permission, rolePermissionBean.permission) &&
        Objects.equals(this.type, rolePermissionBean.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, permission, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RolePermissionBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

